- name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          # Change protocol to 'ftps' to handle modern server handshakes
          protocol: ftps
          # Add this to ignore 'invalid' SSL certificates often found on shared hosting
          secure: false 
          local-dir: ./
          server-dir: /public_html/
